name: Daily News Pipeline

on:
  schedule:
    - cron: '20 2 * * *'   # KST 11:20

jobs:
  daily-pipeline:
    runs-on: ubuntu-latest

    container:
      image: docker.io/sanghoon20/pledge-classifier:latest
      credentials:
        username: ${{ secrets.DOCKERHUB_USER }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}

    env:
      MYSQL_HOST:     ${{ secrets.MYSQL_HOST }}
      MYSQL_PORT:     ${{ secrets.MYSQL_PORT }}
      MYSQL_USER:     ${{ secrets.MYSQL_USER }}
      MYSQL_PASSWORD: ${{ secrets.MYSQL_PASSWORD }}
      MYSQL_DB:       ${{ secrets.MYSQL_DB }}
      POSTGRES_HOST:  ${{ secrets.POSTGRES_HOST }}
      POSTGRES_PORT:  ${{ secrets.POSTGRES_PORT }}
      POSTGRES_USER:  ${{ secrets.POSTGRES_USER }}
      POSTGRES_PASSWORD:   ${{ secrets.POSTGRES_PASSWORD }}
      POSTGRES_DB:    ${{ secrets.POSTGRES_DB }}

    steps:
      - name: Sync Milestones MySQL→Postgres
        run: python sync_milestones.py

      - name: Classify News
        run: python classification.py --batch_size 500

      - name: Aggregate & Update Pledge Status
        run: python aggregate_and_update.py
